server:
  port: 8085

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: upload-service
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 124.221.233.62:8848
